#!/bin/bash
#PBS -V
#PBS -N RColSim
#PBS -q hydro 
#PBS -l nodes=8
#PBS -e /fastscratch/myourek/RColSim_${SCR}.e
#PBS -o /fastscratch/myourek/RColSim_${SCR}.o
#################################################################################
module load r/3.5.3/gcc/7.3.0
Rscript supply_demand.R $SCR $RUN
Rscript flow_to_ColSim.R $SCR $RUN
Rscript RColSim_main.R $SCR $RUN
