#!/bin/bash
#PBS -V
#PBS -N RColSim
#PBS -q hydro 
#PBS -l nodes=8
#################################################################################
module load r/3.5.3/gcc/7.3.0
cd ~/RColSimV2/RColSim  # change to the RColSim parent directory
Rscript supply_demand.R $SCR $RUN
Rscript flow_to_ColSim.R $SCR $RUN
Rscript RColSim_main.R $SCR $RUN
